version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-25250-frontend
    ports:
      - '3030:3030'
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: portfolio-25250-db
    ports:
      - '5433:5433'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolios